apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fpp5fs48c-java-quarkus
  janus-idp.io/tekton: fpp5fs48c-java-quarkus
  backstage.io/kubernetes-id: fpp5fs48c-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fpp5fs48c-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
